version: "3.8"
services:
  mysql:
    image: mysql:8.0
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "3333:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-net
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
  app:
    image: node:16
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: yarn dev
    networks:
      - app-net
    depends_on:
#      - mysql
      mysql:
        condition: service_healthy

networks:
  app-net:
    driver: bridge
volumes:
  mysqldata:
